### ISSUE TITLE
Health endpoint?

### ISSUE THREAD

**Issue by ckapop** [micronaut-projects/micronaut-mqtt#24]
I didn't see any documentation regarding health endpoint support.  I assume it is not implemented as of yet.

If we need to write our own is there a way to call an "isConnected" on the mqtt client? Do we have the ability to inject the client somehow?

**Comment by ckapop** [comment]
So something like this worked just fine:

`  
     @Inject
     public MqttHealthIndicator(MqttAsyncClient mqttClient) {
          this.mqttClient = mqttClient;
     }`

I did notice when using micronaut-mqtt that the server must be running prior to app startup or you get an exception and then the app terminates.

Is there a way to retry and perhaps display a message or something similar? I tried automatic-reconnect: true but it doesn't seem to help.

**Comment by graemerocher** [comment]
HealthIndicator support seems like a good thing to have, contributions welcome!
